<a href="https://colab.research.google.com/github/devPartho3/Mern-Stack-Web-Dev-Marathon-/blob/main/Manual_Hyper_parameter_optimization_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.metrics import accuracy_score

In [ ]:
dataset=pd.read_csv('/breast-cancer.csv')

In [ ]:
dataset.head(5)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
dataset.diagnosis.value_counts()/len(dataset)*100

diagnosis
B    62.741652
M    37.258348
Name: count, dtype: float64

In [ ]:
dataset.shape

(569, 32)

In [ ]:
dataset['diagnosis']=dataset['diagnosis'].map({'M':1,'B':0})

In [ ]:
dataset.head(10)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678
5,843786,1,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,...,15.47,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.1741,0.3985,0.12440
6,844359,1,18.25,19.98,119.60,1040.0,0.09463,0.10900,0.11270,0.07400,...,22.88,27.66,153.20,1606.0,0.1442,0.2576,0.3784,0.1932,0.3063,0.08368
7,84458202,1,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,...,17.06,28.14,110.60,897.0,0.1654,0.3682,0.2678,0.1556,0.3196,0.11510
8,844981,1,13.00,21.82,87.50,519.8,0.12730,0.19320,0.18590,0.09353,...,15.49,30.73,106.20,739.3,0.1703,0.5401,0.5390,0.2060,0.4378,0.10720
9,84501001,1,12.46,24.04,83.97,475.9,0.11860,0.23960,0.22730,0.08543,...,15.09,40.68,97.65,711.4,0.1853,1.0580,1.1050,0.2210,0.4366,0.20750

In [ ]:
x=dataset.iloc[:,[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]]
y=dataset.diagnosis.values

In [ ]:
#train test split

from sklearn.model_selection import train_test_split
x=dataset.drop('diagnosis',axis=1)
y=dataset['diagnosis']
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [ ]:
len(x_train)

426

In [ ]:
len(x_test)

143

In [ ]:
#feature scaling
#standardization
#normalization

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [ ]:
#Model building

from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)

In [ ]:
#matrics

from sklearn.metrics import confusion_matrix,classification_report
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[84  2]
 [ 2 55]]

In [ ]:
result=accuracy_score(y_test,y_pred)
print((result)*100)

97.2027972027972

In [ ]:
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.98      0.98      0.98        86
           1       0.96      0.96      0.96        57

    accuracy                           0.97       143
   macro avg       0.97      0.97      0.97       143
weighted avg       0.97      0.97      0.97       143

In [ ]:
#Manual hyper parameter optimization

n_estimators_list=[1,2,3,10,50,100,200]
for estimlist in n_estimators_list:
  rf=RandomForestClassifier(n_estimators=estimlist)
  rf.fit(x_train,y_train)
  y_pred=rf.predict(x_test)
  result=accuracy_score(y_test,y_pred)
  print(estimlist,':',result)

1 : 0.951048951048951
2 : 0.9090909090909091
3 : 0.9300699300699301
10 : 0.9370629370629371
50 : 0.965034965034965
100 : 0.9790209790209791
200 : 0.972027972027972

In [ ]:
leaf_size=[2,3,4,5,10]
for i in leaf_size:
  rf=RandomForestClassifier(n_estimators=10,max_leaf_nodes=i)
  rf.fit(x_train,y_train)
  y_pred=rf.predict(x_test)
  result=accuracy_score(y_test,y_pred)
  print(i,':',result)

2 : 0.9020979020979021
3 : 0.9300699300699301
4 : 0.951048951048951
5 : 0.9370629370629371
10 : 0.965034965034965

In [ ]:
# Randomsearchcv
n_estimators=[int (x) for x in np.linspace(start=100,stop=1200,num=10)]
max_features=['auto','sqrt']

In [ ]:
n_estimators

[100, 222, 344, 466, 588, 711, 833, 955, 1077, 1200]

In [39]:
from sklearn.model_selection import RandomizedSearchCV
rf=RandomForestClassifier

max_depth=[int(x) for x in np.linspace(5,30,num=11)]
min_samples_split=[2,5,10,15,100]
min_samples_leaf=[1,2,5,10]
bootstrap=[True,False]
random_grid={'n_estimators':n_estimators,
             'max_features':max_features,
             'max_depth':max_depth,
             'min_samples_split': min_samples_split,
             'bootstrap': bootstrap,
             'min_sample_leaf': min_samples_leaf}
print(random_grid)

{'n_estimators': [100, 222, 344, 466, 588, 711, 833, 955, 1077, 1200], 'max_features': ['auto', 'sqrt'], 'max_depth': [5, 7, 10, 12, 15, 17, 20, 22, 25, 27, 30], 'min_samples_split': [2, 5, 10, 15, 100], 'bootstrap': [True, False], 'min_sample_leaf': [1, 2, 5, 10]}

In [42]:
n_estimators=[int (x) for x in np.linspace(start=100,stop=1200,num=10)]
max_features=['sqrt'] # Removed 'auto' as it's no longer a valid option

max_depth=[int(x) for x in np.linspace(5,30,num=11)]
min_samples_split=[2,5,10,15,100]
min_samples_leaf=[1,2,5,10]
bootstrap=[True,False]
random_grid={'n_estimators':n_estimators,
             'max_features':max_features,
             'max_depth':max_depth,
             'min_samples_split': min_samples_split,
             'bootstrap': bootstrap,
             'min_samples_leaf': min_samples_leaf}

rf=RandomForestClassifier()
rf_random=RandomizedSearchCV(estimator=rf,param_distributions=random_grid,scoring='neg_mean_squared_error',n_iter=10,cv=5,verbose=2,random_state=42,n_jobs=1)
rf_random.fit(x_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV] END bootstrap=True, max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END bootstrap=True, max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   0.3s
[CV] END bootstrap=True, max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   0.3s
[CV] END bootstrap=True, max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END bootstrap=True, max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   0.3s
[CV] END bootstrap=False, max_depth=22, max_features=sqrt, min_samples_leaf=10, min_samples_split=10, n_estimators=344; total time=   0.8s
[CV] END bootstrap=False, max_depth=22, max_features=sqrt, min_samples_leaf=10, min_samples_split=10, n_estimators=344; total time=   0.7s
[CV] END bootstrap=False, max_depth=22, max_features=sqrt, min_samples_leaf=10, min_samples_split=10, n_estimators=344; total time=   0.8s
[CV] END bootstrap=False, max_depth=22, max_features=sqrt, min_samples_leaf=10, min_samples_split=10, n_estimators=344; total time=   0.8s
[CV] END bootstrap=False, max_depth=22, max_features=sqrt, min_samples_leaf=10, min_samples_split=10, n_estimators=344; total time=   0.9s
[CV] END bootstrap=False, max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=100, n_estimators=344; total time=   1.0s
[CV] END bootstrap=False, max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=100, n_estimators=344; total time=   0.9s
[CV] END bootstrap=False, max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=100, n_estimators=344; total time=   1.0s
[CV] END bootstrap=False, max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=100, n_estimators=344; total time=   0.7s
[CV] END bootstrap=False, max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=100, n_estimators=344; total time=   0.6s
[CV] END bootstrap=True, max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=5, n_estimators=833; total time=   1.3s
[CV] END bootstrap=True, max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=5, n_estimators=833; total time=   1.3s
[CV] END bootstrap=True, max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=5, n_estimators=833; total time=   1.3s
[CV] END bootstrap=True, max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=5, n_estimators=833; total time=   1.7s
[CV] END bootstrap=True, max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=5, n_estimators=833; total time=   1.7s
[CV] END bootstrap=False, max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=100, n_estimators=588; total time=   1.0s
[CV] END bootstrap=False, max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=100, n_estimators=588; total time=   0.9s
[CV] END bootstrap=False, max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=100, n_estimators=588; total time=   1.0s
[CV] END bootstrap=False, max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=100, n_estimators=588; total time=   0.9s
[CV] END bootstrap=False, max_depth=20, max_features=sqrt, min_samples_leaf=1, min_samples_split=100, n_estimators=588; total time=   1.0s
[CV] END bootstrap=False, max_depth=15, max_features=sqrt, min_samples_leaf=10, min_samples_split=10, n_estimators=222; total time=   0.4s
[CV] END bootstrap=False, max_depth=15, max_features=sqrt, min_samples_leaf=10, min_samples_split=10, n_estimators=222; total time=   0.3s
[CV] END bootstrap=False, max_depth=15, max_features=sqrt, min_samples_leaf=10, min_samples_split=10, n_estimators=222; total time=   0.3s
[CV] END bootstrap=False, max_depth=15, max_features=sqrt, min_samples_leaf=10, min_samples_split=10, n_estimators=222; total time=   0.3s
[CV] END bootstrap=False, max_depth=15, max_features=sqrt, min_samples_leaf=10, min_samples_split=10, n_estimators=222; total time=   0.3s
[CV] END bootstrap=False, max_depth=12, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=1200; total time=   1.9s
[CV] END bootstrap=False, max_depth=12, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=1200; total time=   2.1s
[CV] END bootstrap=False, max_depth=12, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=1200; total time=   2.4s
[CV] END bootstrap=False, max_depth=12, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=1200; total time=   1.9s
[CV] END bootstrap=False, max_depth=12, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=1200; total time=   1.9s
[CV] END bootstrap=True, max_depth=5, max_features=sqrt, min_samples_leaf=5, min_samples_split=15, n_estimators=100; total time=   0.1s
[CV] END bootstrap=True, max_depth=5, max_features=sqrt, min_samples_leaf=5, min_samples_split=15, n_estimators=100; total time=   0.2s
[CV] END bootstrap=True, max_depth=5, max_features=sqrt, min_samples_leaf=5, min_samples_split=15, n_estimators=100; total time=   0.1s
[CV] END bootstrap=True, max_depth=5, max_features=sqrt, min_samples_leaf=5, min_samples_split=15, n_estimators=100; total time=   0.1s
[CV] END bootstrap=True, max_depth=5, max_features=sqrt, min_samples_leaf=5, min_samples_split=15, n_estimators=100; total time=   0.2s
[CV] END bootstrap=True, max_depth=25, max_features=sqrt, min_samples_leaf=2, min_samples_split=15, n_estimators=711; total time=   1.1s
[CV] END bootstrap=True, max_depth=25, max_features=sqrt, min_samples_leaf=2, min_samples_split=15, n_estimators=711; total time=   1.1s
[CV] END bootstrap=True, max_depth=25, max_features=sqrt, min_samples_leaf=2, min_samples_split=15, n_estimators=711; total time=   1.1s
[CV] END bootstrap=True, max_depth=25, max_features=sqrt, min_samples_leaf=2, min_samples_split=15, n_estimators=711; total time=   1.1s
[CV] END bootstrap=True, max_depth=25, max_features=sqrt, min_samples_leaf=2, min_samples_split=15, n_estimators=711; total time=   1.4s
[CV] END bootstrap=True, max_depth=12, max_features=sqrt, min_samples_leaf=10, min_samples_split=5, n_estimators=1200; total time=   2.2s
[CV] END bootstrap=True, max_depth=12, max_features=sqrt, min_samples_leaf=10, min_samples_split=5, n_estimators=1200; total time=   2.0s
[CV] END bootstrap=True, max_depth=12, max_features=sqrt, min_samples_leaf=10, min_samples_split=5, n_estimators=1200; total time=   1.7s
[CV] END bootstrap=True, max_depth=12, max_features=sqrt, min_samples_leaf=10, min_samples_split=5, n_estimators=1200; total time=   2.4s
[CV] END bootstrap=True, max_depth=12, max_features=sqrt, min_samples_leaf=10, min_samples_split=5, n_estimators=1200; total time=   3.3s

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [5, 7, 10, 12, 15, 17, 20,
                                                      22, 25, 27, 30],
                                        'max_features': ['sqrt'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 10, 15,
                                                              100],
                                        'n_estimators': [100, 222, 344, 466,
                                                         588, 711, 833, 955,
                                                         1077, 1200]},
                   random_state=42, scoring='neg_mean_squared_error',
                   verbose=2)

In [62]:
def evaluate(model, test_features, test_labels):
  predictions=model.predict(test_features)
  errors=abs(predictions-test_labels)
  # For classification, MAPE is not suitable if test_labels can be zero.
  # Using sklearn's accuracy_score for classification accuracy.
  accuracy=accuracy_score(test_labels, predictions)*100
  print('Model Performance')
  print('Average Error (misclassification rate):',round(np.mean(errors),2))
  print('Accuracy:',round(accuracy,2),'%')
  return accuracy # Return the accuracy

In [53]:
best_random = rf_random.best_estimator_
evaluate(best_random, x_test, y_test)

Model Performance
Average Error (misclassification rate): 0.03
Accuracy: 97.2 %

In [61]:
basemodel=RandomForestClassifier(n_estimators=5)
basemodel.fit(x_train,y_train)
y_pred=basemodel.predict(x_test)
result=accuracy_score(y_test,y_pred)
base_accuracy = result * 100 # Store the baseline accuracy
print(base_accuracy)

93.7062937062937

In [56]:
bestrandom=rf_random.best_estimator_
bestrandom.fit(x_train,y_train)
y_pred=bestrandom.predict(x_test)
result=accuracy_score(y_test,y_pred)
print(result*100)

97.2027972027972

In [63]:
randomaccuracy=evaluate(bestrandom,x_test,y_test)

Model Performance
Average Error (misclassification rate): 0.03
Accuracy: 97.2 %

In [64]:
print('Improvement of {:0.2f}%.'.format((randomaccuracy - base_accuracy) / base_accuracy * 100))

Improvement of 3.73%.